name: Unit Tests

on:
  push: ~
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    name: Jekyll ${{ matrix.jekyll-versions }} on ubuntu-latest
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    strategy:
      fail-fast: false
      matrix:
        jekyll-versions:
          - "3.5.0"
          - "3.6.0"
          - "3.7.0"
          - "3.8.0"
          - "4.0.0"
          - "4.1.0"
          - "(GitHub Pages)"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install bundler
        run: gem install bundler

      - name: Configure Jekyll
        if: matrix.jekyll-versions != '(GitHub Pages)'
        run: |
          bundle add jekyll --version="~>${{ matrix.jekyll-versions }}"

      - name: Configure Jekyll for GitHub Pages
        if: matrix.jekyll-versions == '(GitHub Pages)'
        run: |
          sudo apt install -y libxslt-dev
          gem install pkg-config
          bundle add github-pages

      - name: Run unit tests
        run: |
          bundle exec jekyll --version
          bundle exec jekyll build
          python plutils/pltest.py

  on_complete:
    name: Notify IRC on Completion
    runs-on: ubuntu-latest
    needs: tests
    if: always()

    steps:
      - name: Send IRC notification
        uses: allejo/supybot-notification-action@v1
        with:
          status: ${{ needs.tests.result }}
          hostname: ${{ secrets.SUPYBOT_HOSTNAME }}
          credentials: ${{ secrets.SUPYBOT_PASSWORD }}
          channel: '#sujevo-dev'
          default_message: true
